name: Deploy to Server

on:
  push:
    branches: [ main ]  # Change this to your main branch name if different (e.g., master)

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /home/aaronstatic/production/aaronstatic-website
            git pull
            docker-compose down
            docker-compose up --build -d 